version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - '📦 Dependencies'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: "react-day-picker"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - '📦 Dependencies'
      - '🚀 CI/CD'
