import "./globals.css";
import { createMetadata } from "@repo/seo/metadata";
import { UIProvider } from "@repo/ui";
import { fonts } from "@repo/ui/lib/fonts";
import type { Metadata } from "next";

const title = "Create Next App";
const description = "Generated by create next app";

export const metadata: Metadata = createMetadata({ title, description });

type RootLayoutProperties = {
  readonly children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProperties) {
  return (
    <html lang="en" className={fonts} suppressHydrationWarning>
      <body>
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
